@startuml
class Contacto {
    -id_contacto: Int
    -nombre: String
    -email: String
    -contraseña: String
    -telefono: Int
    -direccion: String
    -usuario_id: usuario
    +agregarContacto()
    +eliminarContacto()
    +editarContacto()
    +agregarAFavoritos()
    +actualizarContacto()
}

class Usuario {
    -id_usuario: Int
    -nombre: String
    -email: String
    -contraseña: String
    -fecha_registro: DateTime
    +manejarContactos()
    +manejarGrupos()
}

class Categoria {
    -id_categoria: Int
    -nombre: String
    -usuario_id: usuario
    +agregarCategoria()
    +eliminarCategoria()
    +actualizarCategoria()
}

class Contacto_Categoria {
    -id_categoria: categoria
    -id_contacto: contacto
}

Contacto *-- Contacto_Categoria
Usuario --* Contacto
Categoria --* Contacto_Categoria
Usuario --* Categoria
@enduml
